name: ChatItemSprite
version: '${version}'

authors: [ minejango2 ]

main: minej.minejango2.chatitemsprite.ChatItemSpritePlugin
api-version: '26.2'
load: POSTWORLD
dependencies:
  server:
    ItemsAdder:
      load: BEFORE
      required: false
      join-classpath: true
    LuckPerms:
      load: BEFORE
      required: false
      join-classpath: true

permissions:
  chatitemsprite.use:
    description: Allows using the chatitemsprite feature
    default: true
  chatitemsprite.reload:
    description: Allows reloading the chatitemsprite plugin
    default: op
