name: ChatItemSprite
version: '${version}'

authors: [ minejango2 ]

main: minej.minejango2.chatitemsprite.ChatItemSpritePlugin
api-version: '26.2'
load: POSTWORLD
dependencies:
  server:
    ItemsAdder:
      load: BEFORE
      required: false
      join-classpath: true
    Oraxen:
      load: BEFORE
      required: false
      join-classpath: true
    Nexo:
      load: BEFORE
      required: false
      join-classpath: true
    CraftEngine:
      load: BEFORE
      required: false
      join-classpath: true
    LuckPerms:
      load: BEFORE
      required: false
      join-classpath: true

permissions:
  chatitemsprite.use:
    description: Allows using the ChatItemSprite feature
    default: true
  chatitemsprite.command:
    description: Allows using ChatItemSprite commands
    default: op
  chatitemsprite.command.reload:
    description: Allows reloading the ChatItemSprite plugin
    default: op
  chatitemsprite.command.help:
    description: Allows using /chatitemsprite help
    default: op
  chatitemsprite.command.version:
    description: Allows check latest ChatItemSprite version
    default: op
